colors.primary.background = '0x1b182c'
colors.primary.foreground = '0xcbe3e7'

colors.normal.black   = '0x100e23'
colors.normal.red     = '0xff8080'
colors.normal.green   = '0x95ffa4'
colors.normal.yellow  = '0xffe9aa'
colors.normal.blue    = '0x91ddff'
colors.normal.magenta = '0xc991e1'
colors.normal.cyan    = '0xaaffe4'
colors.normal.white   = '0xcbe3e7'


colors.bright.black   = '0x565575'
colors.bright.red     = '0xff5458'
colors.bright.green   = '0x62d196'
colors.bright.yellow  = '0xffb378'
colors.bright.blue    = '0x65b2ff'
colors.bright.magenta = '0x906cff'
colors.bright.cyan    = '0x62f2f1'
colors.bright.white   = '0xa6b3cc'
